#!/usr/bin/env python3
import sys
import os
import argparse
import random
import string

# Page size dimensions in points (1 inch = 72 points)
PAGE_SIZES = {
    "A4": (595, 842),
    "Letter": (612, 792),
    "Legal": (612, 1008),
    "A3": (842, 1191),
    "A5": (420, 595)
}

def parse_size_str(size_str):
    """Parse size string like '5MB', '500KB' into bytes."""
    size_str = size_str.upper().strip()
    if size_str.endswith("MB"):
        return int(float(size_str[:-2]) * 1024 * 1024)
    elif size_str.endswith("KB"):
        return int(float(size_str[:-2]) * 1024)
    elif size_str.endswith("B"):
        return int(float(size_str[:-1]))
    else:
        # Default to MB if just a number is passed
        try:
            return int(float(size_str) * 1024 * 1024)
        except ValueError:
            raise ValueError(f"Invalid size format: '{size_str}'. Use formats like '5MB', '500KB', etc.")

def generate_pdf_pure_python(filename, width=595, height=842, target_file_size=None, page_size_name="A4"):
    """
    Generates a 100% valid PDF file structure with a specific page size (dimensions)
    and optional target file size (by padding with a stream object).
    Does not require any external dependencies.
    """
    # Base text/graphics content inside the PDF page
    content_text = (
        f"BT\n"
        f"/Helvetica 24 Tf\n"
        f"70 750 Td\n"
        f"(PaperVault Test Document) Tj\n"
        f"0 -40 Td\n"
        f"/Helvetica 14 Tf\n"
        f"(Page Size: {page_size_name} ({width} x {height} pt)) Tj\n"
        f"0 -30 Td\n"
        f"(Generated by: PaperVault PDF Generator Utility) Tj\n"
        f"0 -30 Td\n"
    )
    if target_file_size:
        size_mb = target_file_size / (1024 * 1024)
        content_text += f"(Target File Size: {size_mb:.2f} MB) Tj\n"
    content_text += "ET\n"
    
    # 1. Objects initialization
    objects = []
    
    # We will compute byte offsets dynamically to construct a valid xref table.
    def add_object(obj_body):
        obj_id = len(objects) + 1
        objects.append((obj_id, obj_body))
        return f"{obj_id} 0 R"

    # Add objects to stack
    ref_catalog = add_object("<< /Type /Catalog /Pages 2 0 R >>")
    ref_pages = add_object("<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
    ref_page = add_object(f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {width} {height}] /Resources << /Font << /Helvetica << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> >> >> /Contents 4 0 R >>")
    ref_contents = add_object(f"<< /Length {len(content_text)} >>\nstream\n{content_text}endstream")
    
    # 2. Add padding object if a specific file size is targeted
    # We first estimate the file size of the basic PDF without padding
    # Basic PDF elements size estimation:
    header = "%PDF-1.4\n"
    
    # Format all current objects to calculate baseline size
    serialized_objs = {}
    baseline_size = len(header)
    for oid, body in objects:
        serialized = f"{oid} 0 obj\n{body}\nendobj\n"
        serialized_objs[oid] = serialized
        baseline_size += len(serialized)
        
    # Estimate size of trailer, xref, etc. (around 300-400 bytes)
    baseline_size += 400
    
    if target_file_size and target_file_size > baseline_size:
        needed_padding = target_file_size - baseline_size
        # To make it exactly target_file_size, we account for the padding object wrapper overhead
        # Overhead: "5 0 obj\n<< /Length X >>\nstream\n...endstream\nendobj\n" (approx 50 bytes)
        overhead = 60 + len(str(needed_padding))
        actual_padding_len = needed_padding - overhead
        
        if actual_padding_len > 0:
            # Generate dummy printable characters for the padding stream
            padding_data = "x" * actual_padding_len
            pad_body = f"<< /Type /Metadata /Length {actual_padding_len} >>\nstream\n{padding_data}\nendstream"
            add_object(pad_body)

    # 3. Write PDF with actual cross-reference (xref) table
    with open(filename, "wb") as f:
        offsets = {}
        
        # Write header
        f.write(b"%PDF-1.4\n")
        
        # Write objects and record offsets
        for oid, body in objects:
            offsets[oid] = f.tell()
            f.write(f"{oid} 0 obj\n{body}\nendobj\n".encode("utf-8"))
            
        # Write xref table
        xref_start = f.tell()
        f.write(b"xref\n")
        f.write(f"0 {len(objects) + 1}\n".encode("utf-8"))
        f.write(b"0000000000 65535 f \n")
        for oid in range(1, len(objects) + 1):
            offset = offsets[oid]
            f.write(f"{offset:010d} 00000 n \n".encode("utf-8"))
            
        # Write trailer
        f.write(b"trailer\n")
        f.write(f"<< /Size {len(objects) + 1} /Root 1 0 R >>\n".encode("utf-8"))
        f.write(b"startxref\n")
        f.write(f"{xref_start}\n".encode("utf-8"))
        f.write(b"%%EOF\n")

    # Double check final size and adjust if necessary
    final_size = os.path.getsize(filename)
    return final_size

def get_terminal_size():
    try:
        return os.get_terminal_size().columns
    except:
        return 80

def main():
    parser = argparse.ArgumentParser(description="Generate PDF files of customizable page sizes and file sizes.")
    parser.add_argument("-o", "--output", help="Output PDF filename")
    parser.add_argument("-s", "--size", help="Target file size (e.g. '5MB', '250KB')")
    parser.add_argument("-p", "--page", choices=list(PAGE_SIZES.keys()) + ["CUSTOM"], default="A4", help="Page size (A4, Letter, etc.)")
    parser.add_argument("--width", type=int, help="Custom page width in points (used if -p CUSTOM)")
    parser.add_argument("--height", type=int, help="Custom page height in points (used if -p CUSTOM)")
    parser.add_argument("-i", "--interactive", action="store_true", help="Run in interactive CLI mode")

    args = parser.parse_args()
    
    # Default to interactive if no arguments are provided
    if len(sys.argv) == 1 or args.interactive:
        print("\n=== PaperVault PDF Utility ===")
        
        # 1. Page Size Selection
        print("\nSelect Page Size:")
        options = list(PAGE_SIZES.keys()) + ["CUSTOM"]
        for idx, opt in enumerate(options, 1):
            if opt != "CUSTOM":
                w, h = PAGE_SIZES[opt]
                print(f"  {idx}) {opt} ({w} x {h} pt)")
            else:
                # Custom
                print(f"  {idx}) CUSTOM (Enter width/height)")
        
        try:
            choice = int(input("\nEnter choice (1-6) [default: 1 (A4)]: ").strip() or "1")
        except ValueError:
            choice = 1
            
        width, height = PAGE_SIZES["A4"]
        page_name = "A4"
        
        if choice == 2:
            width, height = PAGE_SIZES["Letter"]
            page_name = "Letter"
        elif choice == 3:
            width, height = PAGE_SIZES["Legal"]
            page_name = "Legal"
        elif choice == 4:
            width, height = PAGE_SIZES["A3"]
            page_name = "A3"
        elif choice == 5:
            width, height = PAGE_SIZES["A5"]
            page_name = "A5"
        elif choice == 6:
            page_name = "CUSTOM"
            try:
                width = int(input("Enter width in pt (e.g. 600): ").strip())
                height = int(input("Enter height in pt (e.g. 800): ").strip())
            except ValueError:
                print("Invalid input, using A4 default.")
                width, height = PAGE_SIZES["A4"]
                page_name = "A4"

        # 2. File Size Selection
        print("\nEnter target FILE SIZE (e.g., '10MB', '500KB', or 'none' for default):")
        size_input = input("[default: none]: ").strip()
        target_bytes = None
        if size_input and size_input.lower() != 'none':
            try:
                target_bytes = parse_size_str(size_input)
            except ValueError as e:
                print(f"Error: {e}. Defaulting to standard size.")

        # 3. Filename
        default_filename = f"sample_{page_name.lower()}"
        if target_bytes:
            size_mb = target_bytes / (1024 * 1024)
            if size_mb >= 1:
                default_filename += f"_{int(size_mb)}mb"
            else:
                default_filename += f"_{int(target_bytes/1024)}kb"
        default_filename += ".pdf"
        
        filename = input(f"Enter filename [default: {default_filename}]: ").strip() or default_filename
        
    else:
        # Command line args parsing
        if args.page == "CUSTOM":
            if not args.width or not args.height:
                print("Error: --width and --height are required for CUSTOM page size.")
                sys.exit(1)
            width = args.width
            height = args.height
            page_name = "CUSTOM"
        else:
            width, height = PAGE_SIZES[args.page]
            page_name = args.page
            
        target_bytes = None
        if args.size:
            target_bytes = parse_size_str(args.size)
            
        filename = args.output or f"sample_{page_name.lower()}"
        if target_bytes and not args.output:
            size_mb = target_bytes / (1024 * 1024)
            if size_mb >= 1:
                filename += f"_{int(size_mb)}mb"
            else:
                filename += f"_{int(target_bytes/1024)}kb"
            filename += ".pdf"
        elif not args.output:
            filename += ".pdf"

    # Ensure the filename ends with .pdf extension
    if not filename.lower().endswith(".pdf"):
        filename += ".pdf"

    print(f"\nGenerating PDF: {filename}...")
    try:
        actual_size = generate_pdf_pure_python(filename, width, height, target_bytes, page_name)
        
        # Format the actual printed size nicely
        if actual_size >= 1024 * 1024:
            size_str = f"{actual_size / (1024 * 1024):.2f} MB"
        else:
            size_str = f"{actual_size / 1024:.2f} KB"
            
        print(f"✅ Success! Generated PDF: {filename}")
        print(f"  - Dimensions: {width} x {height} pt ({page_name})")
        print(f"  - Actual File Size: {size_str} ({actual_size} bytes)")
    except Exception as e:
        print(f"❌ Error generating PDF: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
