name:  Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: CI
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
      - name:  Pull latest code
        run: |
          cd ~/nothing
          git fetch origin main
          git reset --hard origin/main

      - name:  build the contianers
        run: |
          cd ~/nothing
          
          echo " Building the containers..."

          docker compose --profile with-nginx build --no-cache

          echo " Containers built successfully."
          
          docker compose --profile with-nginx up -d --remove-orphans

          docker image prune -f
          
          echo " Containers deployed successfully."

      - name:  Health check
        run: |
         sleep 3
          docker ps --format "table {{.Names}}\t{{.Status}}"
          echo " Deployed at $(date)"
