name: 🚀 Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to HPE Server
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
      - name: 📦 Pull latest code
        run: |
          cd ~/cert-verify
          git fetch origin main
          git reset --hard origin/main

      - name: 🎨 build the contianers
        run: |
          cd ~/nothing
          docker compose --profile with-nginx up -d
          docker compose --profile with-nginx up -d --no-deps --force-recreate

      - name: ✅ Health check
        run: |
          sleep 3
          docker ps --format "table {{.Names}}\t{{.Status}}" | grep certverify
          echo "✅ Deployed at $(date)"